# Generated by Django 5.2.7 on 2025-11-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_busroute_reverse_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
