# Generated by Django 5.2.7 on 2025-11-04 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_bus_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickuprequest",
            name="stop_obj",
            field=models.ForeignKey(
                blank=True,
                help_text="The actual Stop object if user selected from route stops",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pickup_requests",
                to="core.stop",
            ),
        ),
    ]
