# Generated by Django 5.2.7 on 2025-11-04 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_pickuprequest_stop_obj"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pickuprequest",
            name="stop_obj",
        ),
        migrations.AddField(
            model_name="pickuprequest",
            name="reserved_seat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="core.seat",
            ),
        ),
    ]
